### ISSUE TITLE
Version available via iobroker.admin seriously outdated

### ISSUE THREAD

**Issue by olifre** [soef/iobroker.yamaha#10]
Hi! 
First off, thanks a lot for this adapter!
The version I get via iobroker admin sadly is still 0.3.5, which in some cases never reconnects for me (for example if the instance was started while the receiver was not connected to the network). 
In the repository here i find a much newer version, and the commits indicate a lot of work has been done mostly on reconnecting etc. 
Could an update be pushed, please? 
Thanks! :-)

**Comment by soef** [comment]
Hi,
I have published version 0.3.12.  I think this Version will be available in ioBroker over night. 

Greetings.

**Comment by olifre** [comment]
Hi! 
Thanks, however, it seems the iobroker server did something strange... 
Looking at:
http://download.iobroker.net/sources-dist.json
I find:
```
  "yamaha": {
    "meta": "https://raw.githubusercontent.com/soef/ioBroker.yamaha/master/io-package.json",
    "icon": "yamaha.png",
    "version": "0.3.5",
    "name": "yamaha",
    "news": {
      "0.3.12": {
        "en": "Version incr. for npm",
        "de": "Version fr npm erhÃ¶ht"
      },
```
i.e. the "news" is updated, but the version is still at "0.3.5".... 
Greetings, 
Oliver

**Comment by soef** [comment]
Hi, I'm using the Onlinesource 
https://raw.githubusercontent.com/ioBroker/ioBroker.js-controller/master/conf/sources-dist.json	

Otherwise you can manually update the Adapter by this commands:
Change to your ioBroker root Directory and 
npm install iobroker.yamaha
iobroker upload yamaha
Now you have to restart the yamaha adapter.

**Comment by olifre** [comment]
Hi! Thanks, with the online-source it works fine! 
Still a bit strange that the default configuration (and thus the majority of users) will not see the new version.

**Comment by Apollon77** [comment]
Do you want to update stable repo?!

Stable Repo still has v 0.3.5. When still the most stable version, everything great, if not please update in stable-repo.

(see https://github.com/ioBroker/ioBroker.repositories)

Thanx for checking

Ingo F

**Comment by soef** [comment]
Ok, i will send a pullrequest
