### ISSUE TITLE
Version 0.3.12: uncaught exception: restart is not defined in yamaha.js line 349

### ISSUE THREAD

**Issue by mschmortte** [soef/iobroker.yamaha#11]
In version 0.3.12 I sometimes get "instance system.adapter.yamaha.0 terminated with code 6 (uncaught exception)" errors because "restart is not defined" in yamaha.js line 349.

**Comment by soef** [comment]
Oh... Is fixed in 0.3.14

**Comment by mschmortte** [comment]
Great, thank you!
