### ISSUE TITLE
PowerOff/Standby does not work

### ISSUE THREAD

**Issue by hieblmedia** [soef/iobroker.yamaha#8]
Model: RX-V473

Standby does not work, but Power-On works.

I dont know how to debug iobroker plugins atm., so i have tested the functionality quckly over HTTP POST and the receiver goes successfullly in Standby:

Tested with:
POST [IP]/YamahaRemoteControl/ctrl
Content: text/xml
`<?xml version="1.0" encoding="utf-8"?><YAMAHA_AV cmd="PUT"><Main_Zone><Power_Control><Power>Standby</Power></Power_Control></Main_Zone></YAMAHA_AV>`

In yamaha.js Standby looks ok. Maybe the wrong zone will be submitted on power off?

Edit:
If i set in IoBroker over Realtime.raw = @MAIN:PWR=Standby it does also work.
Only power=false does not work.

**Comment by soef** [comment]
Hello, I have changed the handling of the power state. Before power=false Switches all zones off, now only the main zone (like power=treu does). further I have renamed the allZone state to powerAllZones.
I hope this will help you.

**Comment by hieblmedia** [comment]
Thanks!
Power does work now fully.
powerAllZones has no effect on my RX-V473, but it has no zones implemented. So it should be fine.
